-- MitthuuG Database Seed Data
-- Populate products table with initial product catalog

-- Insert 6 starter products
INSERT INTO products (
    name,
    slug,
    description,
    short_description,
    price,
    compare_at_price,
    category,
    tags,
    image_url,
    images,
    sku,
    stock,
    weight,
    nutrition_info,
    ingredients,
    allergens,
    rating,
    review_count,
    sold_count,
    is_featured,
    is_active,
    is_new,
    is_bestseller,
    meta_title,
    meta_description
) VALUES 
-- Product 1: Classic Gud Bites
(
    'Classic Gud Bites',
    'classic-gud-bites',
    'Experience the authentic taste of traditional Indian jaggery-based snacks. Our Classic Gud Bites are handcrafted using time-honored recipes passed down through generations. Made with premium-quality jaggery from Maharashtra and enriched with nutrient-dense nuts, these bite-sized treats offer a perfect balance of sweetness and nutrition. Each piece is carefully prepared to maintain the natural goodness of jaggery while delivering an irresistible taste that transports you to the heart of rural India.',
    'Traditional jaggery-based snacks made with authentic Indian recipes. Perfect balance of sweetness and nutrition.',
    149.00,
    199.00,
    'Classic Collection',
    ARRAY['jaggery', 'traditional', 'handmade', 'natural', 'indian sweets'],
    '/products/classic-gud-bites.jpg',
    ARRAY['/products/classic-gud-bites-1.jpg', '/products/classic-gud-bites-2.jpg', '/products/classic-gud-bites-3.jpg'],
    'MG-CGB-250',
    50,
    250.00,
    '{"calories": 120, "protein": "2g", "carbs": "22g", "fat": "3g", "fiber": "1g", "sugar": "18g"}'::jsonb,
    ARRAY['Organic Jaggery', 'Roasted Peanuts', 'Sesame Seeds', 'Ghee', 'Cardamom'],
    ARRAY['Nuts', 'Dairy'],
    4.5,
    128,
    543,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    'Classic Gud Bites - Traditional Jaggery Snacks | MitthuuG',
    'Authentic Indian jaggery-based snacks handcrafted with traditional recipes. Made with organic jaggery and premium nuts. Order online for home delivery.'
),

-- Product 2: Ginger Gud Chikki
(
    'Ginger Gud Chikki',
    'ginger-gud-chikki',
    'Introducing a modern twist on traditional chikki! Our Ginger Gud Chikki combines the warming properties of fresh ginger with the natural sweetness of pure jaggery. This innovative blend not only tantalizes your taste buds but also aids digestion and boosts immunity. The subtle heat from ginger perfectly complements the earthy notes of jaggery, creating a unique flavor profile that is both comforting and invigorating. Ideal for those who appreciate authentic flavors with added health benefits.',
    'Zesty ginger meets golden jaggery in this warming, digestive-friendly chikki. A modern twist on tradition.',
    159.00,
    209.00,
    'Spiced Collection',
    ARRAY['ginger', 'chikki', 'spiced', 'digestive', 'immunity'],
    '/products/ginger-gud-chikki.jpg',
    ARRAY['/products/ginger-gud-chikki-1.jpg', '/products/ginger-gud-chikki-2.jpg'],
    'MG-GGC-250',
    30,
    250.00,
    '{"calories": 115, "protein": "2g", "carbs": "21g", "fat": "2.5g", "fiber": "1g", "sugar": "17g"}'::jsonb,
    ARRAY['Organic Jaggery', 'Fresh Ginger', 'Roasted Peanuts', 'Sesame Seeds', 'Cardamom'],
    ARRAY['Nuts'],
    4.3,
    87,
    312,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    'Ginger Gud Chikki - Healthy Jaggery Snacks | MitthuuG',
    'Delicious ginger-infused jaggery chikki with digestive benefits. Handmade with fresh ginger and organic jaggery. Shop now!'
),

-- Product 3: Coconut Gud Ladoo
(
    'Coconut Gud Ladoo',
    'coconut-gud-ladoo',
    'Indulge in the tropical paradise of our Coconut Gud Ladoo. These heavenly spheres combine freshly grated coconut with premium jaggery, creating a melt-in-your-mouth experience that is simply divine. Each ladoo is meticulously hand-rolled to perfection, ensuring a consistent texture and taste. The natural oils from coconut blend seamlessly with the mineral-rich jaggery, offering both incredible flavor and impressive nutritional value. Perfect for festive celebrations or as a special treat for yourself.',
    'Heavenly spheres of coconut and jaggery that melt in your mouth. Perfect for celebrations.',
    169.00,
    219.00,
    'Premium Collection',
    ARRAY['coconut', 'ladoo', 'festive', 'premium', 'handmade'],
    '/products/coconut-gud-ladoo.jpg',
    ARRAY['/products/coconut-gud-ladoo-1.jpg', '/products/coconut-gud-ladoo-2.jpg', '/products/coconut-gud-ladoo-3.jpg'],
    'MG-CGL-200',
    25,
    200.00,
    '{"calories": 135, "protein": "2g", "carbs": "20g", "fat": "5g", "fiber": "2g", "sugar": "16g"}'::jsonb,
    ARRAY['Fresh Coconut', 'Organic Jaggery', 'Ghee', 'Cardamom', 'Cashews'],
    ARRAY['Nuts', 'Dairy'],
    4.7,
    156,
    428,
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    'Coconut Gud Ladoo - Traditional Indian Sweets | MitthuuG',
    'Premium coconut jaggery ladoos handmade with fresh ingredients. Perfect for festivals and celebrations. Order authentic Indian sweets online.'
),

-- Product 4: Til Gud Barfi
(
    'Til Gud Barfi',
    'til-gud-barfi',
    'Celebrate the essence of winter with our traditional Til Gud Barfi. This seasonal specialty combines nutty sesame seeds with rich jaggery to create a confection that is both delicious and nutritious. Sesame seeds are known for their high calcium content and warming properties, making this barfi perfect for cold weather. The addition of roasted nuts adds a delightful crunch, while jaggery provides natural sweetness and essential minerals. A must-have during Makar Sankranti and throughout the winter season.',
    'Nutty sesame seeds and rich jaggery create this warming winter specialty. High in calcium and iron.',
    179.00,
    229.00,
    'Festival Specials',
    ARRAY['sesame', 'barfi', 'winter', 'festival', 'calcium-rich'],
    '/products/til-gud-barfi.jpg',
    ARRAY['/products/til-gud-barfi-1.jpg', '/products/til-gud-barfi-2.jpg'],
    'MG-TGB-300',
    40,
    300.00,
    '{"calories": 140, "protein": "3g", "carbs": "19g", "fat": "6g", "fiber": "2g", "sugar": "15g"}'::jsonb,
    ARRAY['Sesame Seeds', 'Organic Jaggery', 'Almonds', 'Ghee', 'Cardamom'],
    ARRAY['Nuts', 'Dairy', 'Sesame'],
    4.6,
    203,
    591,
    FALSE,
    TRUE,
    FALSE,
    TRUE,
    'Til Gud Barfi - Sesame Jaggery Sweets | MitthuuG',
    'Traditional til gud barfi made with roasted sesame and organic jaggery. Perfect for Makar Sankranti. Buy authentic Indian sweets.'
),

-- Product 5: Dry Fruit Gud Mix
(
    'Dry Fruit Gud Mix',
    'dry-fruit-gud-mix',
    'Elevate your snacking experience with our luxurious Dry Fruit Gud Mix. This premium blend features a carefully curated selection of the finest dry fruits - almonds, cashews, pistachios, and walnuts - all bound together with pure jaggery. Each bite delivers a symphony of textures and flavors, from the crunch of nuts to the smooth sweetness of jaggery. Rich in omega-3 fatty acids, protein, and antioxidants, this mix is not just indulgent but also incredibly nutritious. The perfect gift for health-conscious food lovers.',
    'Premium blend of finest dry fruits bound with pure jaggery. Luxury meets nutrition.',
    249.00,
    299.00,
    'Premium Collection',
    ARRAY['dry fruits', 'premium', 'luxury', 'gift', 'healthy'],
    '/products/dry-fruit-gud-mix.jpg',
    ARRAY['/products/dry-fruit-gud-mix-1.jpg', '/products/dry-fruit-gud-mix-2.jpg', '/products/dry-fruit-gud-mix-3.jpg'],
    'MG-DFM-300',
    20,
    300.00,
    '{"calories": 160, "protein": "4g", "carbs": "18g", "fat": "8g", "fiber": "3g", "sugar": "14g"}'::jsonb,
    ARRAY['Almonds', 'Cashews', 'Pistachios', 'Walnuts', 'Organic Jaggery', 'Ghee', 'Saffron'],
    ARRAY['Nuts', 'Dairy'],
    4.8,
    94,
    267,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    'Dry Fruit Gud Mix - Premium Jaggery Snacks | MitthuuG',
    'Luxurious dry fruit mix with organic jaggery. Premium almonds, cashews, and pistachios. Perfect gift for health enthusiasts.'
),

-- Product 6: Chocolate Gud Fusion
(
    'Chocolate Gud Fusion',
    'chocolate-gud-fusion',
    'Bridge the gap between traditional and contemporary with our innovative Chocolate Gud Fusion. This groundbreaking creation marries the ancient goodness of jaggery with the beloved flavor of premium dark chocolate. The result is a sophisticated treat that appeals to both traditionalists and modern palates. Rich antioxidants from dark chocolate combine with the mineral wealth of jaggery to create a guilt-free indulgence. Perfect for those who want to enjoy the benefits of traditional ingredients with a contemporary twist.',
    'Ancient jaggery meets premium dark chocolate. A sophisticated fusion of tradition and modernity.',
    189.00,
    239.00,
    'Premium Collection',
    ARRAY['chocolate', 'fusion', 'contemporary', 'dark chocolate', 'innovative'],
    '/products/chocolate-gud-fusion.jpg',
    ARRAY['/products/chocolate-gud-fusion-1.jpg', '/products/chocolate-gud-fusion-2.jpg'],
    'MG-CGF-200',
    35,
    200.00,
    '{"calories": 145, "protein": "3g", "carbs": "20g", "fat": "6g", "fiber": "2g", "sugar": "16g"}'::jsonb,
    ARRAY['Dark Chocolate (70% Cocoa)', 'Organic Jaggery', 'Almonds', 'Cocoa Nibs', 'Sea Salt'],
    ARRAY['Nuts', 'Dairy', 'Soy'],
    4.4,
    112,
    389,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    'Chocolate Gud Fusion - Jaggery Dark Chocolate | MitthuuG',
    'Innovative fusion of organic jaggery and premium dark chocolate. Modern twist on traditional sweets. Shop now!'
);

-- Insert sample coupons
INSERT INTO coupons (
    code,
    description,
    discount_type,
    discount_value,
    min_order_value,
    max_discount_amount,
    usage_limit,
    per_user_limit,
    valid_until,
    is_active
) VALUES
(
    'WELCOME10',
    'Welcome offer: 10% off on your first order',
    'percentage',
    10.00,
    299.00,
    100.00,
    NULL,
    1,
    '2025-12-31 23:59:59+00',
    TRUE
),
(
    'FESTIVE15',
    'Festival special: 15% off on all products',
    'percentage',
    15.00,
    499.00,
    200.00,
    500,
    3,
    '2025-12-31 23:59:59+00',
    TRUE
),
(
    'FLAT50',
    'Flat ₹50 off on orders above ₹500',
    'fixed',
    50.00,
    500.00,
    50.00,
    NULL,
    5,
    '2025-12-31 23:59:59+00',
    TRUE
);

-- Seed complete
SELECT 'Database seeded successfully with 6 products and 3 coupons!' as status;
